# Generated by Django 3.1.3 on 2020-12-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_contact', models.IntegerField(default=10)),
                ('date', models.IntegerField()),
                ('tot_items', models.IntegerField()),
                ('tot_cost', models.IntegerField()),
                ('adress', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(max_length=10)),
                ('product_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('cost_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('cost_price', models.IntegerField()),
                ('aval_stock', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
