# Generated by Django 3.1.3 on 2020-12-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201215_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order',
            field=models.CharField(max_length=50),
        ),
    ]
