# Generated by Django 3.1.3 on 2020-12-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201215_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_agency', models.CharField(max_length=30)),
                ('s_contact', models.IntegerField(default=10)),
                ('s_address', models.CharField(max_length=100)),
            ],
        ),
    ]
